sudo: false

language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageReport

after_success:
  - pip install --user codecov && codecov